In [ ]:
#pip install pandas

In [1]:
import pandas as pd

In [3]:
data = {"name":['Jack','Tom','Emma'],'sex':["male",'male','female'],
"age":[21,23,25],"weight":[56,71,63]}
df = pd.DataFrame(data,index=(10,11,12))
df

    name     sex  age  weight
10  Jack    male   21      56
11   Tom    male   23      71
12  Emma  female   25      63

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df = pd.read_csv("test.csv")
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
0,2005,15,1,Asian,Higher,0.135763,17,0,Moderate,0,1,1,1
1,1197,16,1,Caucasian,Higher,1.989925,0,0,Low,1,0,0,1
2,3343,15,0,Caucasian,NaN,10.588715,15,0,High,0,0,0,1
3,2709,18,1,African American,Some College,16.208658,1,0,High,1,0,0,0
4,1436,18,0,Caucasian,NaN,3.576821,27,0,Low,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,1987,18,1,Caucasian,Some College,8.412605,16,0,High,0,1,0,0
475,1121,18,1,Caucasian,Bachelor,3.170405,12,1,Low,1,1,0,0
476,1284,17,0,Caucasian,High School,5.141922,5,1,Low,0,0,0,0
477,2741,18,1,African American,NaN,10.281614,10,0,High,1,0,0,0
478,2727,18,1,Caucasian,NaN,15.610436,26,0,High,0,0,0,0

In [6]:
df.shape

(479, 13)

In [7]:
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
0,2005,15,1,Asian,Higher,0.135763,17,0,Moderate,0,1,1,1
1,1197,16,1,Caucasian,Higher,1.989925,0,0,Low,1,0,0,1
2,3343,15,0,Caucasian,NaN,10.588715,15,0,High,0,0,0,1
3,2709,18,1,African American,Some College,16.208658,1,0,High,1,0,0,0
4,1436,18,0,Caucasian,NaN,3.576821,27,0,Low,0,1,0,0

In [8]:
df.tail()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
474,1987,18,1,Caucasian,Some College,8.412605,16,0,High,0,1,0,0
475,1121,18,1,Caucasian,Bachelor,3.170405,12,1,Low,1,1,0,0
476,1284,17,0,Caucasian,High School,5.141922,5,1,Low,0,0,0,0
477,2741,18,1,African American,NaN,10.281614,10,0,High,1,0,0,0
478,2727,18,1,Caucasian,NaN,15.610436,26,0,High,0,0,0,0

In [9]:
df.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering'],
      dtype='object')

In [10]:
df.to_excel("test.xlsx",index=False)

In [11]:
df['Age']

0      15
1      16
2      15
3      18
4      18
       ..
474    18
475    18
476    17
477    18
478    18
Name: Age, Length: 479, dtype: int64

In [16]:
df[["Age","Gender"]]

     Age  Gender
0     15       1
1     16       1
2     15       0
3     18       1
4     18       0
..   ...     ...
474   18       1
475   18       1
476   17       0
477   18       1
478   18       1

[479 rows x 2 columns]

In [17]:
df["Age"][0]

np.int64(15)

In [23]:
df.iloc[:, 3:5]

            Ethnicity ParentalEducation
0               Asian            Higher
1           Caucasian            Higher
2           Caucasian               NaN
3    African American      Some College
4           Caucasian               NaN
..                ...               ...
474         Caucasian      Some College
475         Caucasian          Bachelor
476         Caucasian       High School
477  African American               NaN
478         Caucasian               NaN

[479 rows x 2 columns]

In [24]:
df[df["Age"]>22]

Empty DataFrame
Columns: [StudentID, Age, Gender, Ethnicity, ParentalEducation, StudyTimeWeekly, Absences, Tutoring, ParentalSupport, Extracurricular, Sports, Music, Volunteering]
Index: []

In [ ]:
df[df["Age"]<=16]

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
0,2005,15,1,Asian,Higher,0.135763,17,0,Moderate,0,1,1,1
2,3343,15,0,Caucasian,NaN,10.588715,15,0,High,0,0,0,1
5,1322,15,1,Caucasian,High School,17.006354,11,0,Very High,1,0,0,0
6,2473,15,1,Caucasian,Some College,14.372075,23,0,Very High,1,1,0,0
8,1901,15,0,Caucasian,High School,12.190570,13,1,Moderate,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,2884,15,0,African American,Some College,4.023459,25,0,Moderate,1,1,1,0
459,2403,15,0,Caucasian,Some College,6.890118,11,0,High,1,0,0,0
462,2534,15,1,Caucasian,Some College,14.471614,25,0,Low,0,0,0,0
468,2883,15,0,African American,High School,4.402197,2,0,Moderate,1,1,0,1
471,1204,15,1,Asian,Some College,1.784443,12,0,Moderate,1,0,0,0

In [29]:
df[df["Gender"]==0]

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
2,3343,15,0,Caucasian,NaN,10.588715,15,0,High,0,0,0,1
4,1436,18,0,Caucasian,NaN,3.576821,27,0,Low,0,1,0,0
7,2704,17,0,Caucasian,High School,4.286001,14,1,Moderate,1,1,1,0
8,1901,15,0,Caucasian,High School,12.190570,13,1,Moderate,0,0,0,0
11,1576,16,0,African American,Some College,13.762353,25,0,NaN,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2403,15,0,Caucasian,Some College,6.890118,11,0,High,1,0,0,0
466,2899,18,0,African American,Bachelor,7.399978,26,0,Low,0,0,0,0
468,2883,15,0,African American,High School,4.402197,2,0,Moderate,1,1,0,1
473,1421,16,0,African American,Higher,4.188134,20,1,Moderate,0,1,0,0
476,1284,17,0,Caucasian,High School,5.141922,5,1,Low,0,0,0,0

In [30]:
df["Age"].mean()

np.float64(16.517745302713987)

In [31]:
df.isnull()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,False,False,False,False,False,False,False,False,False,False,False,False,False
475,False,False,False,False,False,False,False,False,False,False,False,False,False
476,False,False,False,False,False,False,False,False,False,False,False,False,False
477,False,False,False,False,True,False,False,False,False,False,False,False,False
478,False,False,False,False,True,False,False,False,False,False,False,False,False

In [32]:
df.isnull().sum()

StudentID             0
Age                   0
Gender                0
Ethnicity             0
ParentalEducation    61
StudyTimeWeekly       0
Absences              0
Tutoring              0
ParentalSupport      50
Extracurricular       0
Sports                0
Music                 0
Volunteering          0
dtype: int64

In [34]:
df["ParentalEducation"].fillna("High School")

0            Higher
1            Higher
2       High School
3      Some College
4       High School
           ...
474    Some College
475        Bachelor
476     High School
477     High School
478     High School
Name: ParentalEducation, Length: 479, dtype: object

In [ ]:
df.fillna(0)

In [35]:
df.dropna(axis=0,inplace=True)

In [40]:
df.iloc[3,5] = 18
df.iloc[3,5]

np.float64(18.0)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 371 entries, 0 to 476
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          371 non-null    int64
 1   Age                371 non-null    int64
 2   Gender             371 non-null    int64
 3   Ethnicity          371 non-null    object
 4   ParentalEducation  371 non-null    object
 5   StudyTimeWeekly    371 non-null    float64
 6   Absences           371 non-null    int64
 7   Tutoring           371 non-null    int64
 8   ParentalSupport    371 non-null    object
 9   Extracurricular    371 non-null    int64
 10  Sports             371 non-null    int64
 11  Music              371 non-null    int64
 12  Volunteering       371 non-null    int64
dtypes: float64(1), int64(9), object(3)
memory usage: 40.6+ KB

In [42]:
df.describe()

,StudentID,Age,Gender,StudyTimeWeekly,Absences,Tutoring,Extracurricular,Sports,Music,Volunteering
count,371.000000,371.000000,371.000000,371.000000,371.000000,371.000000,371.000000,371.000000,371.000000,371.000000
mean,2169.708895,16.530997,0.482480,9.897552,14.177898,0.301887,0.415094,0.285714,0.204852,0.164420
std,703.478858,1.110629,0.500368,5.684857,8.375682,0.459696,0.493404,0.452364,0.404138,0.371157
min,1019.000000,15.000000,0.000000,0.001057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1491.500000,16.000000,0.000000,4.945751,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2174.000000,17.000000,0.000000,10.103314,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2795.500000,17.000000,1.000000,15.004372,21.000000,1.000000,1.000000,1.000000,0.000000,0.000000
max,3388.000000,18.000000,1.000000,19.978094,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [43]:
df["Music"].unique()

array([1, 0])

In [44]:
df["Age"].value_counts()

Age
17    103
18     92
15     90
16     86
Name: count, dtype: int64

In [45]:
df.dtypes

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity             object
ParentalEducation     object
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport       object
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
dtype: object

In [51]:
df["Tutoring"] = df["Tutoring"].astype("float16")
df

c:\Users\IMENRAYAN\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering
0,2005,15,1,Asian,Higher,0.135763,17,0.0,Moderate,0,1,1,1
1,1197,16,1,Caucasian,Higher,1.989925,0,0.0,Low,1,0,0,1
3,2709,18,1,African American,Some College,16.208658,1,0.0,High,1,0,0,0
5,1322,15,1,Caucasian,High School,18.000000,11,0.0,Very High,1,0,0,0
6,2473,15,1,Caucasian,Some College,14.372075,23,0.0,Very High,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,1175,18,1,Caucasian,High School,6.586426,20,1.0,Low,1,0,0,0
473,1421,16,0,African American,Higher,4.188134,20,1.0,Moderate,0,1,0,0
474,1987,18,1,Caucasian,Some College,8.412605,16,0.0,High,0,1,0,0
475,1121,18,1,Caucasian,Bachelor,3.170405,12,1.0,Low,1,1,0,0
476,1284,17,0,Caucasian,High School,5.141922,5,1.0,Low,0,0,0,0

In [52]:
df["new"] = df["Music"] + df["Tutoring"]
df

c:\Users\IMENRAYAN\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,new
0,2005,15,1,Asian,Higher,0.135763,17,0.0,Moderate,0,1,1,1,1.0
1,1197,16,1,Caucasian,Higher,1.989925,0,0.0,Low,1,0,0,1,0.0
3,2709,18,1,African American,Some College,16.208658,1,0.0,High,1,0,0,0,0.0
5,1322,15,1,Caucasian,High School,18.000000,11,0.0,Very High,1,0,0,0,0.0
6,2473,15,1,Caucasian,Some College,14.372075,23,0.0,Very High,1,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,1175,18,1,Caucasian,High School,6.586426,20,1.0,Low,1,0,0,0,1.0
473,1421,16,0,African American,Higher,4.188134,20,1.0,Moderate,0,1,0,0,1.0
474,1987,18,1,Caucasian,Some College,8.412605,16,0.0,High,0,1,0,0,0.0
475,1121,18,1,Caucasian,Bachelor,3.170405,12,1.0,Low,1,1,0,0,1.0
476,1284,17,0,Caucasian,High School,5.141922,5,1.0,Low,0,0,0,0,1.0